from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(659, 403)
        icon=QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap('icon.png'),QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 661, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.CheckButton = QtWidgets.QPushButton(self.tab)
        self.CheckButton.setGeometry(QtCore.QRect(360, 176, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.CheckButton.setFont(font)
        self.CheckButton.setObjectName("CheckButton")
        self.UsersAnswerTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.UsersAnswerTextEdit.setGeometry(QtCore.QRect(21, 210, 266, 35))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.UsersAnswerTextEdit.setFont(font)
        self.UsersAnswerTextEdit.setObjectName("UsersAnswerTextEdit")
        self.tasklabel = QtWidgets.QLabel(self.tab)
        self.tasklabel.setGeometry(QtCore.QRect(20, 161, 255, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.tasklabel.setFont(font)
        self.tasklabel.setObjectName("tasklabel")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(20, 10, 591, 134))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.NounRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.NounRadioButton.setGeometry(QtCore.QRect(10, 33, 119, 26))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.NounRadioButton.setFont(font)
        self.NounRadioButton.setObjectName("NounRadioButton")
        self.NounRadioButton.setChecked(True)
        self.VerbRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.VerbRadioButton.setGeometry(QtCore.QRect(10, 66, 75, 26))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.VerbRadioButton.setFont(font)
        self.VerbRadioButton.setObjectName("VerbRadioButton")
        self.AdjectiveRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.AdjectiveRadioButton.setGeometry(QtCore.QRect(10, 99, 98, 26))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.AdjectiveRadioButton.setFont(font)
        self.AdjectiveRadioButton.setObjectName("AdjectiveRadioButton")
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.L15SourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.L15SourceRadioButton.setGeometry(QtCore.QRect(10, 96, 123, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.L15SourceRadioButton.setFont(font)
        self.L15SourceRadioButton.setObjectName("L15SourceRadioButton")
        self.DuolingoSourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.DuolingoSourceRadioButton.setGeometry(QtCore.QRect(10, 64, 92, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.DuolingoSourceRadioButton.setFont(font)
        self.DuolingoSourceRadioButton.setObjectName("DuolingoSourceRadioButton")
        self.AllSourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.AllSourceRadioButton.setGeometry(QtCore.QRect(10, 32, 50, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.AllSourceRadioButton.setFont(font)
        self.AllSourceRadioButton.setObjectName("AllSourceRadioButton")
        self.AllSourceRadioButton.setChecked(True)
        self.L510SourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.L510SourceRadioButton.setGeometry(QtCore.QRect(139, 32, 132, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.L510SourceRadioButton.setFont(font)
        self.L510SourceRadioButton.setObjectName("L510SourceRadioButton")
        self.L1015SourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.L1015SourceRadioButton.setGeometry(QtCore.QRect(139, 64, 141, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.L1015SourceRadioButton.setFont(font)
        self.L1015SourceRadioButton.setObjectName("L1015SourceRadioButton")
        self.L15120SourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.L15120SourceRadioButton.setGeometry(QtCore.QRect(139, 96, 141, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.L15120SourceRadioButton.setFont(font)
        self.L15120SourceRadioButton.setObjectName("L15120SourceRadioButton")
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.NextButton = QtWidgets.QPushButton(self.tab)
        self.NextButton.setGeometry(QtCore.QRect(360, 230, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.NextButton.setFont(font)
        self.NextButton.setObjectName("NextButton")
        self.widget1 = QtWidgets.QWidget(self.tab)
        self.widget1.setGeometry(QtCore.QRect(20, 235, 251, 108))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.solutionlabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.solutionlabel.setFont(font)
        self.solutionlabel.setObjectName("solutionlabel")
        self.verticalLayout.addWidget(self.solutionlabel)
        self.solutionlabel_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.solutionlabel_2.setFont(font)
        self.solutionlabel_2.setObjectName("solutionlabel_2")
        self.verticalLayout.addWidget(self.solutionlabel_2)
        self.solutionlabel_3 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.solutionlabel_3.setFont(font)
        self.solutionlabel_3.setObjectName("solutionlabel_3")
        self.verticalLayout.addWidget(self.solutionlabel_3)
        self.solutionlabel_4 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.solutionlabel_4.setFont(font)
        self.solutionlabel_4.setObjectName("solutionlabel_4")
        self.verticalLayout.addWidget(self.solutionlabel_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        df_all=self.load_data()
        self.on_next_click(df_all)
        self.NextButton.clicked.connect(lambda: self.on_next_click(df_all))
        self.CheckButton.clicked.connect(lambda: self.on_check_click())
        self.NounRadioButton.toggled.connect(lambda: self.on_next_click(df_all))
        self.VerbRadioButton.toggled.connect(lambda: self.on_next_click(df_all))
        self.AdjectiveRadioButton.toggled.connect(lambda: self.on_next_click(df_all))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bokmål"))
        self.CheckButton.setText(_translate("MainWindow", "Check"))
        self.tasklabel.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "Ordforråd"))
        self.NounRadioButton.setText(_translate("MainWindow", "Substantiver"))
        self.VerbRadioButton.setText(_translate("MainWindow", "Verber"))
        self.AdjectiveRadioButton.setText(_translate("MainWindow", "Adjektiver"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Source"))
        self.L15SourceRadioButton.setText(_translate("MainWindow", "Leksjoner 1-5"))
        self.DuolingoSourceRadioButton.setText(_translate("MainWindow", "Duolingo"))
        self.AllSourceRadioButton.setText(_translate("MainWindow", "Alle"))
        self.L510SourceRadioButton.setText(_translate("MainWindow", "Leksjoner 5-10"))
        self.L1015SourceRadioButton.setText(_translate("MainWindow", "Leksjoner 10-15"))
        self.L15120SourceRadioButton.setText(_translate("MainWindow", "Leksjoner 15-20"))
        self.NextButton.setText(_translate("MainWindow", "Next"))
        self.solutionlabel.setText(_translate("MainWindow", "TextLabel"))
        self.solutionlabel_2.setText(_translate("MainWindow", "TextLabel"))
        self.solutionlabel_3.setText(_translate("MainWindow", "TextLabel"))
        self.solutionlabel_4.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "ENG-NOR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "NOR-ENG"))

    def load_data(self):
        url='https://docs.google.com/spreadsheets/d/e/2PACX-1vS06w7mvCUDIZCQklI2cg3-VfhqJPGGMQk-k2Pd3r7W3i2OEkdSIk4BncwP8WiXp8dRQUUEh2ybogA8/pub?output=xlsx'
        df_verbs=pd.read_excel(url, sheet_name='Regelrette verber')
        df_irr_verbs=pd.read_excel(url, sheet_name='Uregelrette verber')
        df_nouns=pd.read_excel(url, sheet_name='Substantiver')
        df_adj=pd.read_excel(url, sheet_name='Adjektiver')
        df_all_verbs=pd.concat([df_verbs, df_irr_verbs], axis=0, ignore_index=True)
        return df_nouns, df_all_verbs, df_adj
    
    def on_next_click(self, df_all):
        if self.NounRadioButton.isChecked():
            sample=df_all[0].sample(n=1)
        elif self.VerbRadioButton.isChecked():
            sample=df_all[1].sample(n=1) 
        elif self.AdjectiveRadioButton.isChecked():
            sample=df_all[2].sample(n=1)
        pair={sample.iloc[0,1]:sample.iloc[0,0]}
        key=list(pair.keys())[0]
        self.tasklabel.setText(sample.iloc[0,1])
        self.solutionlabel.setText(sample.iloc[0,0])
        self.solutionlabel.hide()
        self.solutionlabel_2.hide()
        self.solutionlabel_3.hide()
        self.solutionlabel_4.hide()
        self.UsersAnswerTextEdit.clear()
    
    def on_check_click(self):
        self.solutionlabel.show()
        # self.solutionlabel_2.show()
        # self.solutionlabel_3.show()
        # self.solutionlabel_4.show()
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())