from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 443)
        icon=QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap('icon.png'),QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 921, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.CheckButton = QtWidgets.QPushButton(self.tab)
        self.CheckButton.setGeometry(QtCore.QRect(460, 180, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.CheckButton.setFont(font)
        self.CheckButton.setObjectName("CheckButton")
        self.UsersAnswerTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.UsersAnswerTextEdit.setGeometry(QtCore.QRect(21, 210, 401, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.UsersAnswerTextEdit.setFont(font)
        self.UsersAnswerTextEdit.setMouseTracking(False)
        self.UsersAnswerTextEdit.setObjectName("UsersAnswerTextEdit")
        self.tasklabel = QtWidgets.QLabel(self.tab)
        self.tasklabel.setGeometry(QtCore.QRect(21, 181, 401, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.tasklabel.setFont(font)
        self.tasklabel.setObjectName("tasklabel")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 260, 401, 130))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.solutionlabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.solutionlabel.setFont(font)
        self.solutionlabel.setObjectName("solutionlabel")
        self.verticalLayout.addWidget(self.solutionlabel)
        self.solutionlabel_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.solutionlabel_2.setFont(font)
        self.solutionlabel_2.setObjectName("solutionlabel_2")
        self.verticalLayout.addWidget(self.solutionlabel_2)
        self.solutionlabel_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.solutionlabel_3.setFont(font)
        self.solutionlabel_3.setObjectName("solutionlabel_3")
        self.verticalLayout.addWidget(self.solutionlabel_3)
        self.solutionlabel_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.solutionlabel_4.setFont(font)
        self.solutionlabel_4.setObjectName("solutionlabel_4")
        self.verticalLayout.addWidget(self.solutionlabel_4)
        self.solutionlabel_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.solutionlabel_5.setFont(font)
        self.solutionlabel_5.setObjectName("solutionlabel_5")
        self.verticalLayout.addWidget(self.solutionlabel_5)
        self.solutionlabel_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.solutionlabel_6.setFont(font)
        self.solutionlabel_6.setObjectName("solutionlabel_6")
        self.verticalLayout.addWidget(self.solutionlabel_6)
        self.solutionlabel_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.solutionlabel_7.setFont(font)
        self.solutionlabel_7.setObjectName("solutionlabel_7")
        self.verticalLayout.addWidget(self.solutionlabel_7)
        self.NextButton = QtWidgets.QPushButton(self.tab)
        self.NextButton.setGeometry(QtCore.QRect(460, 260, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.NextButton.setFont(font)
        self.NextButton.setObjectName("NextButton")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 11, 611, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.NounRadioButton = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.NounRadioButton.setFont(font)
        self.NounRadioButton.setObjectName("NounRadioButton")
        self.NounRadioButton.setChecked(True)
        self.verticalLayout_2.addWidget(self.NounRadioButton)
        self.VerbRadioButton = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.VerbRadioButton.setFont(font)
        self.VerbRadioButton.setObjectName("VerbRadioButton")
        self.verticalLayout_2.addWidget(self.VerbRadioButton)
        self.AdjectiveRadioButton = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.AdjectiveRadioButton.setFont(font)
        self.AdjectiveRadioButton.setObjectName("AdjectiveRadioButton")
        self.verticalLayout_2.addWidget(self.AdjectiveRadioButton)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.AllSourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.AllSourceRadioButton.setFont(font)
        self.AllSourceRadioButton.setObjectName("AllSourceRadioButton")
        self.gridLayout.addWidget(self.AllSourceRadioButton, 0, 0, 1, 1)
        self.AllSourceRadioButton.setChecked(True)
        self.A1SourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.A1SourceRadioButton.setFont(font)
        self.A1SourceRadioButton.setObjectName("A1SourceRadioButton")
        self.gridLayout.addWidget(self.A1SourceRadioButton, 1, 0, 1, 1)
        self.A21920SourceRadioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.A21920SourceRadioButton_3.setFont(font)
        self.A21920SourceRadioButton_3.setObjectName("A21920SourceRadioButton_3")
        self.gridLayout.addWidget(self.A21920SourceRadioButton_3, 2, 2, 1, 1)
        self.A21618SourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.A21618SourceRadioButton.setFont(font)
        self.A21618SourceRadioButton.setObjectName("A21618SourceRadioButton")
        self.gridLayout.addWidget(self.A21618SourceRadioButton, 1, 2, 1, 1)
        self.A21215ourceRadioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.A21215ourceRadioButton_2.setFont(font)
        self.A21215ourceRadioButton_2.setObjectName("A21215ourceRadioButton_2")
        self.gridLayout.addWidget(self.A21215ourceRadioButton_2, 0, 2, 1, 1)
        self.LA1911SourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.LA1911SourceRadioButton.setFont(font)
        self.LA1911SourceRadioButton.setObjectName("LA1911SourceRadioButton")
        self.gridLayout.addWidget(self.LA1911SourceRadioButton, 2, 1, 1, 1)
        self.LA158SourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.LA158SourceRadioButton.setFont(font)
        self.LA158SourceRadioButton.setObjectName("LA158SourceRadioButton")
        self.gridLayout.addWidget(self.LA158SourceRadioButton, 1, 1, 1, 1)
        self.LA115SourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.LA115SourceRadioButton.setFont(font)
        self.LA115SourceRadioButton.setObjectName("LA115SourceRadioButton")
        self.gridLayout.addWidget(self.LA115SourceRadioButton, 0, 1, 1, 1)
        self.A2SourceRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.A2SourceRadioButton.setFont(font)
        self.A2SourceRadioButton.setObjectName("A2SourceRadioButton")
        self.gridLayout.addWidget(self.A2SourceRadioButton, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.UsersAnswerTextEdit, self.CheckButton)
        MainWindow.setTabOrder(self.CheckButton, self.NounRadioButton)
        MainWindow.setTabOrder(self.NounRadioButton, self.VerbRadioButton)
        MainWindow.setTabOrder(self.VerbRadioButton, self.AdjectiveRadioButton)
        MainWindow.setTabOrder(self.AdjectiveRadioButton, self.AllSourceRadioButton)
        MainWindow.setTabOrder(self.AllSourceRadioButton, self.A1SourceRadioButton)
        MainWindow.setTabOrder(self.A1SourceRadioButton, self.tabWidget)
        
        dfs=self.load_data()
        self.on_next_click(dfs)
        self.NextButton.clicked.connect(lambda: self.on_next_click(dfs))
        self.CheckButton.clicked.connect(lambda: self.on_check_click())
        self.NounRadioButton.toggled.connect(lambda: self.on_next_click(dfs))
        self.VerbRadioButton.toggled.connect(lambda: self.on_next_click(dfs))
        self.AdjectiveRadioButton.toggled.connect(lambda: self.on_next_click(dfs))
        self.LA158SourceRadioButton.toggled.connect(lambda: self.on_next_click(dfs))
        self.LA1911SourceRadioButton.toggled.connect(lambda: self.on_next_click(dfs))
        self.A21215ourceRadioButton_2.toggled.connect(lambda: self.on_next_click(dfs))
        self.A21618SourceRadioButton.toggled.connect(lambda: self.on_next_click(dfs))
        self.A21920SourceRadioButton_3.toggled.connect(lambda: self.on_next_click(dfs))
        self.A2SourceRadioButton.toggled.connect(lambda: self.on_next_click(dfs))
        self.A1SourceRadioButton.toggled.connect(lambda: self.on_next_click(dfs))
        self.AllSourceRadioButton.toggled.connect(lambda: self.on_next_click(dfs))
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bokmål"))
        self.CheckButton.setText(_translate("MainWindow", "Check"))
        self.tasklabel.setText(_translate("MainWindow", "TextLabel"))
        self.solutionlabel.setText(_translate("MainWindow", "TextLabel"))
        self.solutionlabel_2.setText(_translate("MainWindow", "TextLabel"))
        self.solutionlabel_3.setText(_translate("MainWindow", "TextLabel"))
        self.solutionlabel_4.setText(_translate("MainWindow", "TextLabel"))
        self.solutionlabel_5.setText(_translate("MainWindow", "TextLabel"))
        self.solutionlabel_6.setText(_translate("MainWindow", "TextLabel"))
        self.solutionlabel_7.setText(_translate("MainWindow", "TextLabel"))
        self.NextButton.setText(_translate("MainWindow", "Next"))
        self.groupBox.setTitle(_translate("MainWindow", "Ordforråd"))
        self.NounRadioButton.setText(_translate("MainWindow", "Substantiver"))
        self.VerbRadioButton.setText(_translate("MainWindow", "Verber"))
        self.AdjectiveRadioButton.setText(_translate("MainWindow", "Adjektiver"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Source"))
        self.AllSourceRadioButton.setText(_translate("MainWindow", "Alle ord"))
        self.A1SourceRadioButton.setText(_translate("MainWindow", "A1"))
        self.A21920SourceRadioButton_3.setText(_translate("MainWindow", "Leksjoner 19-20 (A2)"))
        self.A21618SourceRadioButton.setText(_translate("MainWindow", "Leksjoner 16-18 (A2)"))
        self.A21215ourceRadioButton_2.setText(_translate("MainWindow", "Leksjoner 12-15 (A2)"))
        self.LA1911SourceRadioButton.setText(_translate("MainWindow", "Leksjoner 9-11 (A1)"))
        self.LA158SourceRadioButton.setText(_translate("MainWindow", "Leksjoner 6-8 (A1)"))
        self.LA115SourceRadioButton.setText(_translate("MainWindow", "Leksjoner 1-5 (A1)"))
        self.A2SourceRadioButton.setText(_translate("MainWindow", "A2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "ENG-NOR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "NOR-ENG"))

    def load_data(self):
        url='https://docs.google.com/spreadsheets/d/e/2PACX-1vS06w7mvCUDIZCQklI2cg3-VfhqJPGGMQk-k2Pd3r7W3i2OEkdSIk4BncwP8WiXp8dRQUUEh2ybogA8/pub?output=xlsx'
        sheets=['Regelrette verber','Uregelrette verber', 'Substantiver', 'Adjektiver']
        all_df=[pd.read_excel(url, sheet_name = sheet, na_filter=False) for sheet in sheets]
        all_df[0]=pd.concat([all_df[0], all_df[1]], axis=0, ignore_index=True) # concat regular and irregular verbs in one df
        del all_df[1] #deleteing df with irregular verbs
        return all_df

    def on_next_click(self, all_df):
        self.solutionlabel.hide()
        self.solutionlabel_2.hide()
        self.solutionlabel_3.hide()
        self.solutionlabel_4.hide()
        self.solutionlabel_5.hide()
        self.solutionlabel_6.hide()
        self.solutionlabel_7.hide()
            
        if self.NounRadioButton.isChecked():
            sample=self.check_source(all_df[1])
            self.tasklabel.setText(str(sample['Translation'].values[0]))
            self.solutionlabel.setText(str(sample['Ubestemt form'].values[0]))
            self.solutionlabel_2.setText(str(sample['Bestemt form'].values[0]))
            self.solutionlabel_3.setText(str(sample['Flertall Ubestment form'].values[0]))
            self.solutionlabel_4.setText(str(sample['Flertall Bestment form'].values[0]))
        elif self.VerbRadioButton.isChecked():
            sample=self.check_source(all_df[0])
            self.tasklabel.setText(str(sample['Translation'].values[0]))
            self.solutionlabel.setText(str(sample['Infinitive'].values[0]))
            self.solutionlabel_2.setText(str(sample['Presens'].values[0]))
            self.solutionlabel_3.setText(str(sample['Preteritum'].values[0]))
            self.solutionlabel_4.setText(str(sample['Presens perfektum'].values[0]))
        elif self.AdjectiveRadioButton.isChecked():
            sample=self.check_source(all_df[2])
            self.tasklabel.setText(str(sample['Translation'].values[0]))
            self.solutionlabel.setText(str(sample['Original'].values[0]))
            self.solutionlabel_2.setText(str(sample['Neuter'].values[0]))
            self.solutionlabel_3.setText(str(sample['Plural'].values[0]))
            self.solutionlabel_4.setText(str(sample['Definite'].values[0]))
        else:
            raise ValueError ('None of Ordforråd buttons is checked')
        
        self.solutionlabel.setText(sample.iloc[0,0])
        self.solutionlabel.hide()
        self.solutionlabel_2.hide()
        self.solutionlabel_3.hide()
        self.solutionlabel_4.hide()
        self.UsersAnswerTextEdit.clear()
            
        
    def on_check_click(self):
        self.solutionlabel.show()
        self.solutionlabel_2.show()
        self.solutionlabel_3.show()
        self.solutionlabel_4.show()
        
    def check_source (self, df):
        if self.AllSourceRadioButton.isChecked():
            sample=df.sample(n=1)
        elif self.LA115SourceRadioButton.isChecked():
            sample=df[df['Source'].isin(['Leksjoner 1-5'])].sample(n=1)
        elif self.LA158SourceRadioButton.isChecked():
            sample=df[df['Source'].isin(['Leksjon 6', 'Leksjon 7', 'Leksjon 8'])].sample(n=1)
        elif self.LA1911SourceRadioButton.isChecked():
            sample=df[df['Source'].isin(['Leksjon 9', 'Leksjon 10', 'Leksjon 11'])].sample(n=1)
        elif self.A1SourceRadioButton.isChecked():
            sample=df[df['Source'].isin(['Leksjoner 1-5', 'Leksjon 6', 'Leksjon 7', 'Leksjon 8', 'Leksjon 9', 'Leksjon 10', 'Leksjon 11'])].sample(n=1)
        elif self.A21215ourceRadioButton_2.isChecked():
            sample=df[df['Source'].isin(['Leksjon 12', 'Leksjon 13', 'Leksjon 14', 'Leksjon 15'])].sample(n=1)
        elif self.A21618SourceRadioButton.isChecked():
            sample=df[df['Source'].isin(['Leksjon 16', 'Leksjon 17', 'Leksjon 18'])].sample(n=1)
        elif self.A21920SourceRadioButton_3.isChecked():
            sample=df[df['Source'].isin(['Leksjon 19', 'Leksjon 20'])].sample(n=1)
        elif self.A2SourceRadioButton.isChecked():
            sample=df[df['Source'].isin(['Leksjon 12', 'Leksjon 13', 'Leksjon 14', 'Leksjon 15', 'Leksjon 16', 'Leksjon 17', 'Leksjon 18', 'Leksjon 19' , 'Leksjon 20'])].sample(n=1)    
        else:
            raise ValueError('Source not found')
        return sample
            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
